"""start-drift.sh differs from the recipe's start.sh by exactly one opt-in overlay block before the image step."""
import runpy
from pathlib import Path
import pytest

derive = runpy.run_path(str(Path(__file__).resolve().parents[1] / "scripts/deploy_qwen38/start_drift.py"))["derive"]
RULE = "# " + "-" * 75
RECIPE = f"""#!/bin/bash
add_overlay() {{ :; }}
{RULE}
# 4e. FP8 KV cache.
{RULE}
echo overlays
{RULE}
# 5. Ensure Docker image on both nodes
{RULE}
echo launch
"""


def test_the_block_lands_before_the_image_section_and_nothing_else_changes():
    out = derive(RECIPE)
    assert out.startswith("#!/bin/bash\n# Generated by the Drift repository from start.sh sha256 ")
    body = out.split("\n", 2)[2]
    assert body.index("echo overlays") < body.index("DRIFT_CONNECTOR_DIR") < body.index("# 5. Ensure Docker image")
    removed = body.replace(body[body.index(f"{RULE}\n# Drift:"):body.index(f"{RULE}\n# 5. Ensure")], "")
    assert "#!/bin/bash\n" + removed == RECIPE
    assert 'add_overlay "$drift_file" "/usr/local/lib/python3.12/dist-packages/' in out


@pytest.mark.parametrize("recipe", [RECIPE.replace("# 5. Ensure Docker image on both nodes", "# 5. Pull images"),
                                    RECIPE.replace("add_overlay()", "overlay()"),
                                    RECIPE + "\n# DRIFT_CONNECTOR_DIR\n"])
def test_a_changed_recipe_is_refused(recipe):
    with pytest.raises(ValueError):
        derive(recipe)
