"""Derive docker-compose.dspark-drift.yml from the DeepSeek V4 recipe's compose file: the same service plus the Drift connector.

It adds read-only mounts of the connector modules into the image's site-packages and one --kv-transfer-config argument to
the vllm serve command, and turns off expandable CUDA segments, which vLLM refuses alongside a KV connector because the
allocator can remap the cache's physical pages. The launcher copies COMPOSE_FILE to every worker, so pointing COMPOSE_FILE at the derived file
reaches both ranks; each host needs the same connector directory. The recipe checkout itself is never modified.
"""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path

MODULES = ("vllm_raw_rows.py", "drift_spans.py", "raw_rows.py", "glm_allocation_lifecycle.py")
SITE = "/usr/local/lib/python3.12/dist-packages"
ALLOCATOR = 'PYTORCH_CUDA_ALLOC_CONF: "${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"'
CONFIG = {"kv_connector": "DriftRawRowConnector", "kv_role": "kv_producer", "kv_connector_module_path": "vllm_raw_rows",
          "engine_id": "dsv4-drift", "kv_connector_extra_config": {"drift_path": "/dev/shm/drift-rows"}}


def derive(source: str, connector_dir: str) -> str:
    lines = source.splitlines(keepends=True)
    volumes = [i for i, line in enumerate(lines) if line.rstrip("\n") == "    volumes:"]
    chunked = [i for i, line in enumerate(lines) if line.strip() == "--enable-chunked-prefill"]
    serve = [i for i, line in enumerate(lines) if "exec /usr/local/bin/vllm serve" in line]
    if len(volumes) != 1 or len(chunked) != 1 or len(serve) != 1 or not serve[0] < chunked[0]:
        raise ValueError("the recipe's compose anchors moved; review docker-compose.dspark.yml before deriving")
    if "kv-transfer-config" in source or "kv_transfer_config" in source:
        raise ValueError("the compose file already configures a KV connector")
    indent = lines[chunked[0]][: len(lines[chunked[0]]) - len(lines[chunked[0]].lstrip())]
    mounts = [f"      - {connector_dir}/{name}:{SITE}/{name}:ro\n" for name in MODULES]
    argument = f"{indent}--kv-transfer-config '{json.dumps(CONFIG, separators=(',', ':'))}'\n"
    digest = hashlib.sha256(source.encode()).hexdigest()
    allocator = [i for i, line in enumerate(lines) if line.strip() == ALLOCATOR]
    if len(allocator) > 1 or sum("expandable_segments:True" in line for line in lines) != len(allocator):
        raise ValueError("the recipe enables expandable segments in a way this derivation does not know; review it")
    for i in allocator:                                              # vLLM refuses KV connectors on remappable CUDA memory
        lines[i] = lines[i].replace(ALLOCATOR, 'PYTORCH_CUDA_ALLOC_CONF: "expandable_segments:False"')
    out = lines[: volumes[0] + 1] + mounts + lines[volumes[0] + 1: chunked[0] + 1] + [argument] + lines[chunked[0] + 1:]
    return f"# Generated by the Drift repository from docker-compose.dspark.yml sha256 {digest}; regenerate after the recipe changes.\n" + "".join(out)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("recipe", type=Path, help="the DeepSeek V4 recipe checkout")
    parser.add_argument("--connector-dir", default="/root/drift-live/dsv4-connector")
    args = parser.parse_args()
    target = args.recipe / "docker-compose.dspark-drift.yml"
    target.write_text(derive((args.recipe / "docker-compose.dspark.yml").read_text(), args.connector_dir))
    print(f"wrote {target}")
