"""Derive start-drift.sh from the Qwen3.8 recipe's start.sh: identical except one block that overlays the Drift connector.

The block runs only when DRIFT_CONNECTOR_DIR is set, after the recipe's own overlays and before its image step, and uses the
recipe's add_overlay so the modules reach both ranks. The recipe checkout itself is never modified.
"""
from __future__ import annotations
import argparse
import hashlib
from pathlib import Path

ANCHOR = "# 5. Ensure Docker image on both nodes"
RULE = "# " + "-" * 75
BLOCK = f"""{RULE}
# Drift: overlay the Drift KV connector modules onto the containers' Python path.
{RULE}
if $DO_LAUNCH && [[ -n "${{DRIFT_CONNECTOR_DIR:-}}" ]]; then
    info "=== Drift connector overlay ==="
    for drift_file in "$DRIFT_CONNECTOR_DIR"/*.py; do
        add_overlay "$drift_file" "/usr/local/lib/python3.12/dist-packages/$(basename "$drift_file")"
    done
    ok "Drift connector: $(ls "$DRIFT_CONNECTOR_DIR"/*.py | wc -l) modules from $DRIFT_CONNECTOR_DIR"
fi

"""


def derive(source: str) -> str:
    lines = source.splitlines(keepends=True)
    hits = [i for i, line in enumerate(lines) if line.rstrip("\n") == ANCHOR]
    if len(hits) != 1 or hits[0] == 0 or lines[hits[0] - 1].rstrip("\n") != RULE:
        raise ValueError("the recipe's image section anchor moved; review start.sh before deriving start-drift.sh")
    if "add_overlay()" not in source or "DRIFT_CONNECTOR_DIR" in source:
        raise ValueError("start.sh lacks add_overlay or already mentions the Drift overlay")
    digest = hashlib.sha256(source.encode()).hexdigest()
    head, rest = lines[:hits[0] - 1], lines[hits[0] - 1:]
    if not head or not head[0].startswith("#!"):
        raise ValueError("start.sh has no interpreter line")
    note = f"# Generated by the Drift repository from start.sh sha256 {digest}; regenerate after the recipe changes.\n"
    return head[0] + note + "".join(head[1:]) + BLOCK + "".join(rest)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("recipe", type=Path, help="the Qwen3.8 recipe checkout")
    args = parser.parse_args()
    target = args.recipe / "start-drift.sh"
    target.write_text(derive((args.recipe / "start.sh").read_text()))
    target.chmod(0o755)
    print(f"wrote {target}")
